# Generated by Django 5.1.3 on 2026-09-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_identifier', '0007_planthistory_is_correct'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planthistory',
            name='unique_history_per_user',
        ),
    ]
